name: my first workflow

on: [push]

jobs: 
  echo:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, World!"

  pwd-ls:
    name: pwd and ls
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al
        
 